### ISSUE TITLE
[1.17.1] Do not works in server - failed to find method 'registerElytraLayer'

### ISSUE THREAD

**Issue by Sharku2011** [DrunkBlood/Netherite-Elytra#10]
registerElytraLayer is defined in client only. Is it attended?

> -- Head --
> Thread: main
> Stacktrace:
> 	at drunkblood.netheriteelytra.NetheriteElytra.<init>(NetheriteElytra.java:49) ~[netherelytra-base-1.0.0-1.17.1.jar%2343!:base-1.0.0-1.17.1] {re:classloading,pl:runtimedistcleaner:A}
> -- MOD netherelytra --
> Details:
> 	Caused by 0: java.lang.reflect.InvocationTargetException
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {}
> 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.97.jar%2354!:?] {}
> 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.97.jar%2353!:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
> 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
> 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
> 
> 	Mod File: netherelytra-base-1.0.0-1.17.1.jar
> 	Failure message: Netherite Elytra (netherelytra) has failed to load correctly
> 		java.lang.reflect.InvocationTargetException: null
> 	Mod Version: 1.0.1-1.17.1
> 	Mod Issue URL: https://github.com/DrunkBlood/Netherite-Elytra/issues
> 	Exception message: java.lang.NoSuchMethodError: 'void drunkblood.netheriteelytra.NetheriteElytra.registerElytraLayer(net.minecraftforge.client.event.EntityRenderersEvent)'
> Stacktrace:
> 	at drunkblood.netheriteelytra.NetheriteElytra.<init>(NetheriteElytra.java:49) ~[netherelytra-base-1.0.0-1.17.1.jar%2343!:base-1.0.0-1.17.1] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.97.jar%2354!:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.97.jar%2353!:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

**Comment by DrunkBlood** [comment]
try version 1.0.1 I could reproduce the bug and fix it with one line of code

**Comment by Sharku2011** [comment]
It fixed. Thank you!
