### ISSUE TITLE
[1.16.5] [netherelytra-curios-1.0.2-1.16.5] Mod failed to load during the load_registries phase

### ISSUE THREAD

**Issue by TheRealGramdalf** [DrunkBlood/Netherite-Elytra#12]
[latest.log](https://github.com/DrunkBlood/Netherite-Elytra/files/8073978/latest.log)
[crash-2022-02-15_11.05.15-fml.txt](https://github.com/DrunkBlood/Netherite-Elytra/files/8073982/crash-2022-02-15_11.05.15-fml.txt)

The game won't load properly, and gives me a message about the load_registries phase. Log files & crash report above. This is when I tried adding it to a preexisting modpack, vaulthunters (by iskall85). Curios was in by default, and I added curious elytra and curios of undying as well. I tried disabling the elytra and undying mod, but it didn't seem to work. This is using multiMC and adoptium JDK, since the default java wouldn't run that specific modpack. I believe it is java 17.

**Comment by DrunkBlood** [comment]
I could reproduce the bug and fixed it with 1.1.2-1.16.5. I could start valuthunters with all mods and Netherite Elytra curious.
