### ISSUE TITLE
Netherite Elytra Not Compatible with back slot.

### ISSUE THREAD

**Issue by liltoby** [DrunkBlood/Netherite-Elytra#13]
Hello, 

I was wondering if you could make it compatible with https://www.curseforge.com/minecraft/mc-mods/curious-elytra so i can wear it with my armour.

I am on 1.17.1 forge.

Thank you :)

**Comment by liltoby** [comment]
Closing as there was 2 version for 1.17.1, i had the version that wasn't compatible. It has already been made compatible.

I appreciate your work :)

**Comment by liltoby** [comment]
Re opening as the curious version crashes the game. I have tried both 1.17.1 version.
![image](https://user-images.githubusercontent.com/100544552/155910439-36cb3612-4179-4e07-a17d-71036baaba71.png)
[crash-2022-02-28_01.35.31-fml.txt](https://github.com/DrunkBlood/Netherite-Elytra/files/8149945/crash-2022-02-28_01.35.31-fml.txt)

**Comment by DrunkBlood** [comment]
fixed in 1.1.1-curious
