### ISSUE TITLE
Extend mod compatibility

### ISSUE THREAD

**Issue by ricksouth** [DrunkBlood/Netherite-Elytra#4]
Hey! Great mod. I was wondering if you could make your custom Elytra extend ElytraItem instead of Item? This would make it compatible with my mod (https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff) but also with other mods in the future.

Because someone requested it here: https://github.com/ricksouth/serilum-mc-mods/issues/235

**Comment by DrunkBlood** [comment]
The release for 1.16.3 has the minimal change. Thx for the information

**Comment by ricksouth** [comment]
Great!
