### ISSUE TITLE
[1.16.5] Class loading error server crash

### ISSUE THREAD

**Issue by ocram9** [DrunkBlood/Netherite-Elytra#7]
When I start my server it crashes on startup because of a class loading error.

Crash report: https://gist.github.com/ocram9/8e38bc9d32e6a84d4a4aeca17cfa7c49

- Forge 36.1.3
- Minecraft 1.16.5
- Nether-elytra: 1.0.0-1.16.5

**Comment by DrunkBlood** [comment]
I could reproduce the bug and localy it is fixed with version 1.0.1
