### ISSUE TITLE
[1.16.5] Incompatibility with curious-elytra

### ISSUE THREAD

**Issue by ocram9** [DrunkBlood/Netherite-Elytra#8]
I can't load my server with curious elytra and this mod installed. It doesn't crash but according to the logs the server "can't proceed with server load".

Logs: https://gist.github.com/ocram9/7273e3cc0828506ed704bbcc69557972

Netherite-Elytra version: netherelytra-curios-1.0.0-1.16.5
curiouselytra version: curiouselytra-forge-1.16.5-4.0.2.3
Forge 36.1.32

**Comment by DrunkBlood** [comment]
I tested this with the newest curios elytra version and my mod. I could reproduce the issue and it should be fixed in version 1.0.1-curios. Test that version out https://www.curseforge.com/minecraft/mc-mods/netherite-elytra/files/3363023

**Comment by ocram9** [comment]
That fixed it, thanks!
